### ISSUE TITLE
Social Discounts & Compare Products reset each-others settings

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/edd-social-discounts#21] opened 2018-06-28 03:32 UTC
Updating Social Discounts settings resets Compare Products' settings. This happens the other way around as well.

Here are the steps to recreate:

1. Install Social Discounts and Compare Products
2. Got to Social Discounts settings and replace default "Share To Unlock Message" text with any custom text.
3. Go to Compare Products settings and add a field to the Meta fields area (anything will do) & save changes.
4. Return to Social Discount settings and observe the "Share To Unlock Message". This should have returned to default text.
5. Replace default "Share To Unlock Message" text with any custom text.
6. Return to Compare Products and observe the newly-added Meta field disappeared.

**Comment by dgoldak** [comment] 2018-06-28 16:00
@pippinsplugins & @cklosowski Customer is requesting a refund if we cannot fix this in the next couple weeks since he cannot use both extensions at the same time. Is this something we can try to fix ASAP? 

https://secure.helpscout.net/conversation/605750081/84620?folderId=1847242

**Comment by pippinsplugins** [comment] 2018-06-28 16:03
@dgoldak we can fix. I'll take care of it in a few hours. It's an easy fix.

**Comment by pippinsplugins** [comment] 2018-06-28 17:54
I think the problem is actually caused by this function in Compare Products: https://github.com/easydigitaldownloads/edd-compare-products/blob/master/includes/settings.php#L186

**Comment by pippinsplugins** [comment] 2018-06-28 18:38
Bug is in Compare Products, closing.

**Closed by pippinsplugins** 2018-06-28 18:38 UTC
Labels: bug
